name: nightly-run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - run: go run main.go
